server:
  port: 8082

logging:
  level:
    org.springframework:
      security: debug
      web: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

